### ISSUE TITLE
Event Pax not showing correctly on event list page

### ISSUE THREAD

**Issue by Superbestron** [Superbestron/Orbital_2021_FriendZone#33]
For the events that the user has created, sometimes after viewing the event details and going back to the event list page, the shown pax is always less than the actual pax. However, all other fields load correctly except this.

**Comment by yongxiangng** [comment]
This is certainly a bug. However, I was only able to reproduce this bug while on dev. This bug is not reproducible when the app is built and ran on an actual device. This suggests that the bug is either due to the emulator or some buggy behavior in dev mode which doesn't happen after building the apk. Regardless, this is not an issue with our code quality.

**Comment by Superbestron** [comment]
Fixed this bug #41
